{{- range .Values.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: my-kafka-cluster
spec:
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
{{- end }}